# Generated by Django 3.2.6 on 2021-08-18 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.classes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False, verbose_name='Положительная отметка пользователя')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отметка пользователя',
                'verbose_name_plural': 'Отметки пользователей',
                'db_table': 'recommendations_vote',
            },
            bases=(utils.classes.ProjectClass, models.Model),
        ),
    ]
