# Generated by Django 3.2.6 on 2021-08-18 19:50

from django.db import migrations, models
import utils.classes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Прием пищи',
                'verbose_name_plural': 'Приемы пищи',
                'db_table': 'common_food_intake',
            },
            bases=(utils.classes.ProjectClass, models.Model),
        ),
    ]
